apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  labels:
    app: edustream-payment-service
data:
  MONGO_URL: mongodb+srv://clintps1010:KlciMnq03nToZ7tD@cluster0.nj7at.mongodb.net/EduSEduStream_Paymenttream_Course?retryWrites=true&w=majority&appName=Cluster0
  PORT: "4004"
  ACCESS_TOKEN_SECRET: "educationStream!#6675634756ghfghhrthbe4ygb54by46yb54yb"
  REFRESH_TOKEN_SECRET: "educationStream!#548456793789ghfghb4y35bye46ywv54y6yb45y"
  STRIPE_ENDPOINT_SECRET: "whsec_22097adac29c7fb02eb108beb432ab639c3d08643d447b93ea9bc0aef0117473"
  STRIPE_SECRET: "sk_test_51Q0dRxRxGaFOTDjMeplcXAHSubs6MCLO8MqKVrtFa9HE5aZXoxFMMcjYaZAzEG6w9BXcCsV0RZbQKUjjP6XxeFZR00VUOV7gjT"

  FRONTEND_URL: "https://edu-stream-client.vercel.app"
  NODE_ENV: "production"